### ISSUE TITLE
Add CSS scoping issues in IE11 to readme and docs!

### ISSUE THREAD

**Issue by SheepFromHeaven** [biotope/biotope-element#109]
Currently IE11 does not allow css scoping. This means we have to take care of css scoping by classes or ids. This should be mentioned in the docs somewhere.

**Comment by dannystey** [comment]
@SheepFromHeaven Maybe you already heard about it, but i would like to show up the principles of css modules... maybe that could be a generic solution for scoping styles and share global styles through components. https://css-tricks.com/css-modules-part-1-need/

**Comment by jurekbarth** [comment]
@dannystey that would be indeed a nice addition, but imho it would not be part of biotope element.
