### ISSUE TITLE
Just a visual issue - missing 🐤 in readme.md

### ISSUE THREAD

**Issue by simonbraunbrown** [biotope/biotope-element#119]
just because I recognized it and it has confused me visually. I missed a chick 🐤 after the first Hello World.

![Bildschirmfoto 2019-05-08 um 11 22 48](https://user-images.githubusercontent.com/48211993/57365415-50b2e080-7185-11e9-95fa-188611302ea2.png)

**Comment by timomayer** [comment]
So true! Do you wanna send a PR?

**Comment by simonbraunbrown** [comment]
@timomayer sure :)
