### ISSUE TITLE
Prevent me of not using reservated Attribute names

### ISSUE THREAD

**Issue by hummelch** [biotope/biotope-element#155]
**Is your feature request related to a problem? Please describe.**
Attributes like title are reservated of html and shouldn‘t / don‘t work with bio-element 

**Describe the solution you'd like**
When I use such a Attribute, I get Feedback in the console that it will not work!

**Comment by tiagomapmarques** [comment]
@hummelch Can you verify that these are the attributes you're talking about?
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes
Just to be clear, biotope-element should output a console warning when these attributes are used. Is that it? If so, @biotope/core-enforcer:

Q: Should we just start using `data-*` attributes instead?
Q: Should this warning/check be done in biotope-quality-gate instead?

**Comment by pmpinto** [comment]
> Q: Should we just start using data-* attributes instead?

Wouldn't that go against:

> These attributes are not intended for use by software that is independent of the site that uses the attributes.
Ref: https://www.w3.org/TR/2011/WD-html5-20110525/elements.html#embedding-custom-non-visible-data-with-the-data-attributes

It seems to me `data-*` attributes are meant to be used by in-site features and not 3rd party software.
Is there a reason not to use proprietary/namespaced attributes like `bio-*`?

**Comment by tiagomapmarques** [comment]
This seems to no longer be a problem with biotope-element v4.
Will investigate further and close the issue if this is the case.

**Comment by tiagomapmarques** [comment]
Confirmed that attributes "title" and "lang" (2 native html attributes) can be overridden both in the DOM and through nested components. Also tested modifying the "title" attribute to be parsed as an array of strings instead of a string. No bugs or errors found on IE11 or Chrome.

Closing the issue as the problem does seem to have been resolved in v4.
