### ISSUE TITLE
Add upgrade guide (from v3 to v4) to documentation

### ISSUE THREAD

**Issue by timomayer** [biotope/biotope-element#172]
before we publish latest version which includes breaking changes. We need an easy to follow upgrade guide to ensure developers upgrade to latest version.

**Comment by timomayer** [comment]
Think we should also add examples of how to use bioelement 3 and bioelement 4 in parallel in a project so you can use v4 for new components and v3 for existing once

**Comment by tiagomapmarques** [comment]
Fixed by #198.
