### ISSUE TITLE
Add polyfills for IE11 and Edge - Documentation

### ISSUE THREAD

**Issue by christophsaile** [biotope/biotope-element#214]
Hello,

can someone please change the **Add polyfills for IE11 and Edge - section** of the biotope-element docu.
In my opinion the following instruction can lead to a wrong folder structure:

> Copy the following files from node_modules/@webcomponents to src/resources/js/polyfills
> 'webcomponents-loader.js',
> 'bundles/webcomponents-ce.js',
> 'bundles/webcomponents-sd-ce-pf.js',
> 'bundles/webcomponents-sd-ce.js',
> 'bundles/webcomponents-sd.js'

In my case I copied all the files to `src/resources/js/polyfills` instead of some of them into the `src/resources/js/polyfills/bundles` folder.
Thats why I suggest an instruction like this for example.

> Copy the following file from node_modules/@webcomponents to src/resources/js/polyfills
> 
> `'webcomponents-loader.js'`
> 
> and copy the following files from node_modules/@webcomponents to src/resources/js/polyfills/bundles
> 
> ```
> 'bundles/webcomponents-ce.js',
> 'bundles/webcomponents-sd-ce-pf.js',
> 'bundles/webcomponents-sd-ce.js',
> 'bundles/webcomponents-sd.js'
> ```

Another option would be to host the `webcomponents-loader.js`  &  `object-assign.polyfill.js` via unpkg.com.

This way you only have to add some lines to the `htmlhead.scripts.hbs` file:

```
<script nomodule src="https://unpkg.com/whatwg-fetch"></script>
<script nomodule src="https://unpkg.com/promise-polyfill"></script>
<script nomodule src="https://unpkg.com/object-assign-polyfill"></script>

<script src="resources/js/vendor/custom-elements-es5-adapter.js"></script>
<script src="https://unpkg.com/@webcomponents/webcomponentsjs/webcomponents-loader.js"></script>
```
and modify the `projectConfig.js`:
```
global: {
  externalResources: {
    '@webcomponents/webcomponentsjs': [
      'custom-elements-es5-adapter.js'
    ]
  }
  uglify: {
    ignoreList: [
      'src/resources/js/polyfills/object-assign.polyfill.js',
      'resources/js/vendor/custom-elements-es5-adapter.js',
    ]
  }
}
```

**Comment by tiagomapmarques** [comment]
Fixed by the current examples under the `examples` folder (`examples/src/index.html`) and the new documentation (#236)
