### ISSUE TITLE
Revamped and more streamlined docs

### ISSUE THREAD

**Issue by tiagomapmarques** [biotope/biotope-element#233]
**Is your feature request related to a problem? Please describe.**
Our documentation
- feels disorganised/disjointed
- lacks a landing page
- lacks the "one-directional" explanation of biotope-element

**Describe the solution you'd like**
A revamped documentation!

**Comment by carmelag** [comment]
Hi! I would like to help with the documentation enhancement. The current documentation is not clear  to a user that has never heard about this project. I would add a soft introduction to the main features and purposes and then I would go through a documentation review. Working step-by-step following the process that a user would goes through, we can see what it’s missing on that. Please let me know if some help is still wanted here :-)

**Comment by tiagomapmarques** [comment]
Hi @carmelag, I actually put the "help wanted" label but had some time to work on it.

You can help us review [this PR](#236) and look for typos, missing info and not-so-well-explained concepts :)

You can have a look at the online page [here](https://deploy-preview-236--biotope-element.netlify.com/docs/next/). Maybe this helps the review.
