### ISSUE TITLE
Remove the 3rd argument on the emit() function

### ISSUE THREAD

**Issue by pmpinto** [biotope/biotope-element#242]
**Is your feature request related to a problem? Please describe.**
Reading the documentation about emitting events there's this block of code:
```
this.emit('pressed', 'Super secret value', true);
```

If I understood correctly, using this code inside a `my-button` component will result in the `my-button-pressed` event being dispatched, instead of `pressed` as stated in the 1st argument.

**Describe the solution you'd like**
Remove the 3rd argument altogether. If you want to change the name of the event, do it manually and explicitly so other developers don't need to know about the conventions/magic behind the scenes.

**Describe alternatives you've considered**
None.

**Additional context**
NA.

**Comment by tiagomapmarques** [comment]
Fixed by #243.
