### ISSUE TITLE
update readme.md to link to documentation

### ISSUE THREAD

**Issue by timomayer** [biotope/biotope-element#253]

**Comment by tiagomapmarques** [comment]
Is this ok or should we do something else?
[readme doc link](https://github.com/biotope/biotope-element#documentation)

![image](https://user-images.githubusercontent.com/704002/69449033-c95c4180-0d51-11ea-9877-45c0a7d21aa5.png)

**Comment by timomayer** [comment]
sorry for not beeing clear, i dont like the mix of having a small documntation in the md file and a larger one external so i vote for removing the quick start guide or at least place the documentation link more top in the readme.md
