### ISSUE TITLE
[Shadow DOM] Use elements not resolved when SVG is nested in shadow root

### ISSUE THREAD

**Issue by dweiger** [biotope/biotope-element#43]
See folowing BUG for Safari:

https://bugs.webkit.org/show_bug.cgi?id=174977

What do you think about that?

**Comment by SheepFromHeaven** [comment]
https://github.com/w3c/webcomponents/issues/179

**Comment by rniwa** [comment]
FWIW, the bug is fixed in the latest iOS & macOS betas.

**Comment by jurekbarth** [comment]
As we cannot fix this behaviour i'll close here.
