### ISSUE TITLE
Dashed attributes does not work as expected

### ISSUE THREAD

**Issue by dweiger** [biotope/biotope-element#61]
**Describe the bug**
If I use a dashed attributes it does not work if set on the Custom Element

**To Reproduce**
1. Set in your Props a neede Property:

interface MyProps {
aToDashProperty: string;
}

2. Register it as an Attribute with dashes.
 static attributes = ['a-to-dash-property'];

3. set the property on your Element:
<my-element a-to-dash-property="Hello world"></my-element>

4. Use the property with this.props.aToDashProperty
For example use it in the Rendermethod to display.

**Expected behavior**
The Component shows my attribute value where it is needed.

**Desktop (please complete the following information):**

**Additional context**
This is what I understood from the Docu. Please Correct me if I got something wrong.

**Comment by SheepFromHeaven** [comment]
@dweiger you are absolutely right. I followed your steps to reproduce and it works for me.
```
<hello-world a-to-dash-property="Hello World"></hello-world>
```
and
```
class HelloWorld extends Component<HelloWorldProps, HelloWorldState> {
    static componentName = 'hello-world';

    static attributes = ['a-to-dash-property'];

    render() {
        return template(this.html, {
            prop: this.props.aToDashProperty
        });
    }
}
```

works for me fine

**Comment by dweiger** [comment]
Works for me with update to version 2.0.2
