### ISSUE TITLE
domtagger error after yarn install

### ISSUE THREAD

**Issue by bennyvi** [biotope/biotope-element#73]
**To Reproduce**
1. install with 'yarn add' 
2. start serve with yarn/(npm) start
3. check the debugging console (F12)
4. See Domtagger Error

**Comment by jurekbarth** [comment]
It doesn‘t happen using npm, we should add e2e tests in order to test against these kind if issues.

**Comment by jurekbarth** [comment]
I'll close this as i cannot reproduce 👍 Please reopen if necessary.
