### ISSUE TITLE
Polyfills not loading in ie11 on first visit

### ISSUE THREAD

**Issue by dweiger** [biotope/biotope-element#90]
**Describe the bug**
Sometimes the polyfills for webcomponents seem not to be loaded initially

**To Reproduce**
Clean the cache and open  a polyfilled webcomponent in ie11.

**Expected behavior**
Evrything should look as expected (compare with chrome)

**Desktop (please complete the following information):**
 - IE11

**Additional context**
I'm not sure if this bug is at the right place here. If not let me know where to report it.

**Comment by jurekbarth** [comment]
@dweiger i guess it belongs more to biotope-boilerplate as biotope-element is not polyfilling web components itself 😃
Anyway have you tried resizing your IE11 after the page has loaded?

**Comment by SheepFromHeaven** [comment]
@dweiger any updates here?

**Comment by dweiger** [comment]
At the moment the issue does not exist anymore. I am on element version 2.0.2 and build version 6.1.0-0. 
I would close this issue if no one else can reproduce this.
