### ISSUE TITLE
Converter arrow function won't work with curly braces

### ISSUE THREAD

**Issue by no-creative-name** [biotope/biotope-element#95]
**Description**
When passing in an attribute that should not be treated as a string, you have to convert it with a converter function. If you are using an arrow function with curly braces for the converter, using the attribute won't work.

**Steps to reproduce the behavior:**
1. Pass in attribute that should not be treated as a string (e.g. number)
2. Add to attributes variable in component class
3. Add arrow function as converter with curly braces around the function block.
4. Try to use attribute parameter

**Expected behavior**
You should be able to use curly braces around the function block, since the converter function could be more complex than just one command.

**Screenshots**
Works: 
![image](https://user-images.githubusercontent.com/25197658/54015468-11194980-4180-11e9-9b54-c1a7799b5e7d.png)
Does not work: 
![image](https://user-images.githubusercontent.com/25197658/54015486-1b3b4800-4180-11e9-9a12-ba3af5f4e571.png)

**Desktop (please complete the following information):**
 Win10, Chrome

**Comment by jurekbarth** [comment]
This is because an arrow function has an implicit return as long as you're not using curly braces. If you use them you would need to explicitly return something in this case:
```
{name: 'number-attribute', converter: (value) => {return parseInt(value, 10)}}
```
